[package]
name = "agbox-workgraph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
test-support = ["agbox-core/test-support"]

[dependencies]
agbox-core.workspace = true
blake3.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true

[dev-dependencies]
agbox-core = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
